// Generated by Finicky Kickstart
// Save as ~/.finicky.js

module.exports = {
  defaultBrowser: "Google Chrome",
  handlers: [
    { // 少数派
      match: /^https:\/\/sspai\.com\/.*$/,
      browser: "Vivaldi"
    },
    { // IFTTT
      match: /^https:\/\/ift\.tt\/.*$/,
      browser: "Vivaldi"
    },
    { // Zapiar
      match: /^https:\/\/zapier\.com\/.*$/,
      browser: "Vivaldi"
    }
  ]
}