# Don't print a new line at the start of the prompt
add_newline = false

# Replace the "❯" symbol in the prompt with "➜"
[character]                            # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)"     # The "success_symbol" segment is being set to "➜" with the color "bold green"
error_symbol = "[✗](bold red) "

[kubernetes]
format = 'on [⛵ $context \($namespace\)](dimmed green) '
disabled = false
[kubernetes.context_aliases]
"minikube" = "local"
"kubernetes-admin@cluster.local" = "172.19.80.11"

#[aws]
#symbol = " "

[battery]
full_symbol = ""
charging_symbol = ""
discharging_symbol = ""

#[conda]
#symbol = " "

#[dart]
#symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

#[haskell]
#symbol = " "

[helm]
format = "via [⎈ $version](bold white) "

[hg_branch]
symbol = " "

#[java]
#symbol = " "

#[julia]
#symbol = " "

[memory_usage]
symbol = " "

#[nim]
#symbol = " "

#[nix_shell]
#symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

#[perl]
#symbol = " "

#[php]
#symbol = " "

[python]
symbol = " "

#[ruby]
#symbol = " "

[rust]
symbol = " "

[shell]
fish_indicator = ""
powershell_indicator = "_"
disabled = false

[swift]
symbol = "ﯣ "

[time]
disabled = false
format = '[\[$time\]]($style) '
time_format = "%T"
utc_time_offset = "+8"
